services:
  - type: web
    name: bulloch-transport
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python -m app.main
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0